### PR TITLE
Develop cleanup

### PR DESCRIPTION
**Pull request by logicplace**
Taking care of cleanup bits from review. Haven't been any other suggestions so I'm opening the PR. Once this is in develop, we can merge the MVP PR to master, too.

### CODE REVIEW

**Comment by something15525** [comment]
Looks great to me! :ship:

**Comment by ghost** [comment]
Looks great!

**Comment by logicplace** [comment]
Okay fixed the submodule (tested, worked for me at least) but had to force push of course.

**Comment by ghost** [comment]
I still can't get mine working. Pulled changes and followed readme (submodule command worked this time). What am I missing?

btw I'm still getting the same three errors as before:

leaflet-idw.js:1 -- Uncaught SyntaxError: Unexpected token .
dashboard.js:54 -- Uncaught TypeError: L.idwLayer is not a function
leaflet.js:6 -- Uncaught TypeError: Cannot read property '_leaflet_id' of undefined

**Comment by something15525** [comment]
@logicplace just tried this PR on the web server, no luck. Getting the same errors as Eric.

**Comment by something15525** [comment]
I've updated the README to account for the setup of the core.symlinks feature and the submodule. After performing these commands, I was able to get the frontend working successfully on a Linux machine.

**Comment by logicplace** [comment]
Submodule's being too much of a pain I guess, removed it. Not _that_ important.

**Comment by something15525** [comment]
Looks good to me! :ship:

**Pull request merged**
