### PR TITLE
FE#53: Multi-vineyard support

### PR DESCRIPTION
**Pull request by something15525**
This adds frontend support for multiple vineyards with one user.

Requires https://github.com/Plantalytics/plantalytics-backend/pull/57

### CODE REVIEW

**Comment by something15525** [comment]
Fixes https://github.com/Plantalytics/plantalytics-frontend/issues/53

**Comment by logicplace** [comment]
Going to complain heavily about the use of a select element. Stylistically pretty much all HTML form elements have been deprecated (except input type text and button).

It should be pretty simple to add regular menu entry elements to the menu at that point. See http://api.jquery.com/after/ Can help if needed.

**Comment by logicplace** [comment]
Is there an account with multiple views I can test with? Tested with username at least and having the one looks good.

**Comment by something15525** [comment]
@logicplace you should be able to use
Username: multivineyarder
Password: multipass

**Comment by logicplace** [comment]
Okay great. I tried to do this at the airport yesterday but couldn't connect to the DB for some reason. Everything's working from new home internet though and it looks good!

Feature suggestion for a future iteration though: Maybe we could make the client remember which vineyard the user was last on to load that one on login.

**Comment by logicplace** [comment]
By we I mean someone else of course.

**Pull request merged**
