### PR TITLE
FE#50 Change password

### PR DESCRIPTION
**Pull request by something15525**
How to get to it:
Click gear then click "Change Password"

Steps to test:
- [ ] Try with correct current password and new password
- [ ] Try with incorrect current password and new password
- [ ] Try with correct or incorrect current password and new password, but different text than new password in the confirm password field.

### CODE REVIEW

**Comment by something15525** [comment]
This fixes #50

**Comment by stripes416** [comment]
Just tested.
Shows error if new passwords aren't the same, but otherwise doesn't do anything. I've checked the db, nothing gets updated with valid current & new passwords. Also, success message doesn't show. Is this the expected behavior? Looking at the code, I don't think so, but then again ... its time to sleep. Let me know if there is something I'm missing.

**Comment by stripes416** [comment]
#ignoreME, It was a local issue, totally my bad.
As I said, it was time to sleep.

I totally give my ack'd, you'll want someone else to double check it, cause apparently I need moar caffeine to notice things at 2:15 am.

**Comment by scotte216** [comment]
I don't know much about JS, but when I inspect the page and do change requests it seems to have multiple (6-8) POSTs and responses from the /change endpoint. By contrast when the 'forgot password' just made/received 1. I don't know if this is any kind of problem or issue, but figured I should point it out.

**Comment by scotte216** [comment]
Okay, so it's definitely causing a problem (these multiple POSTS). The first POST will go through, change the password (in fact the first 6 go through successfully) then the subsequent ones will then fail, since the 'old password' is now different (since it was successfully changed). 

It kind of seems like the number of POSTs is increasing the more I change the password, like it's adding one POST each time.

**Comment by scotte216** [comment]
Example server responses for 1 password change request:
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 200 0
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 200 0
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 200 0
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 200 0
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 200 0
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 200 0
[05/Aug/2016 11:28:25] "POST /password/change HTTP/1.1" 400 61
[05/Aug/2016 11:28:26] "POST /password/change HTTP/1.1" 400 61
[05/Aug/2016 11:28:26] "POST /password/change HTTP/1.1" 400 61
[05/Aug/2016 11:28:26] "POST /password/change HTTP/1.1" 400 61
[05/Aug/2016 11:28:26] "POST /password/change HTTP/1.1" 400 61

**Comment by something15525** [comment]
Yeah, I think I know what's going on. The click listener for the Change Password button in the form is being added every time the "Change Password" button is being clicked in the gear menu. I'll fix this tonight and push up fix, then we can retest. Thanks @scotte216!

**Comment by something15525** [comment]
@scotte216 feel free to take another gander!

**Comment by scotte216** [comment]
I'll check it out shortly!

**Comment by scotte216** [comment]
:wine_glass:

**Pull request merged**
