### PR TITLE
FE#20: Login styling adjustments

### PR DESCRIPTION
**Pull request by kbrimm**
Updated login styling to match dashboard color scheme. Moved logo.png to images folder.

### CODE REVIEW

**Comment by ScottEwing** [comment]
:shipit: Looks good to me!

**Comment by logicplace** [comment]
I don't know, I liked the lower contrast colours from before. It was a bit calmer, more personable. This doesn't look bad or anything, though. I might try the original login theme on the dashboard before merging this.

**Comment by kbrimm** [comment]
Cool. Either way is fine by me.

**Comment by scotte216** [comment]
Usability comment: When I enter my user name I then hit 'tab' to go to passwords. Instead it goes to the question mark instead. Any way to change the tab order preference? Very low priority.

**Comment by logicplace** [comment]
I think there's an html tag for it but it may be more appropriate to just make the ? a non-tabbable element. Like a span rather than an anchor.

**Pull request merged**
