### PR TITLE
FE#21 styling adjustments

### PR DESCRIPTION
**Pull request by logicplace**

### CODE REVIEW

**Comment by something15525** [comment]
So to clarify, this isn't fixing the space, right? Also, I would suggest not having a divider for an non-existent item if that makes sense. Having more spacing on the top and bottom of each item would be great, without the extra divider. I can take a shot at it if you'd like.

**Comment by something15525** [comment]
Also, was able to verify that the menu animates faster.

**Comment by something15525** [comment]
Spoke too soon, was able to reproduce the bug once again. No issues present in the console, besides a warning about google maps api:

util.js:211 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by something15525** [comment]
Here's a screenshot of the bug. The weird black rectangle is the inflated menu.

inflation_bug

**Comment by logicplace** [comment]
I can remove the spacer, but it wasn't part of the plan no. It was my groping at making the menu look less compact. More margin works too I guess.

**Comment by kbrimm** [comment]
I vote more margin!

**Comment by logicplace** [comment]
Well tried that, do you want more? How much more if so??

**Comment by kbrimm** [comment]
That amount is delightful! I also like the faster animation. :+1:

**Comment by SoySauceLabs** [comment]
tbh, I hadn't looked at the current state of the dashboard until just now, but I like it! Good work y'all!

**Comment by something15525** [comment]
Looks great @logicplace ! Were you able to reproduce the inflation issue? Just click a bunch of times in succession and then try to inflate/deflate the menu.

**Comment by something15525** [comment]
The above commit should fix it. @logicplace if you could confirm.

**Comment by logicplace** [comment]
You can reduce this to $menu.is(":animated") instead of using a variable.

**Comment by something15525** [comment]
Alright, i'll fix this tonight.

**Comment by logicplace** [comment]
Sure, thanks for spotting it.

**Comment by something15525** [comment]
Alright, I tried that implementation and the UI bug resurfaced. Keeping the boolean implementation since it works and the $menu.is('animated') function does not. I think we're good to go ahead and merge this.

**Comment by logicplace** [comment]
What browser are you using? !$menu.is(":animated") is working for me in Chrome.

**Comment by logicplace** [comment]
Also just noticed you indented everything by 2 instead of 4.

**Comment by something15525** [comment]
Using chrome as well. And Atom did that for me. Had we settled on a style yet? Should we be using tabs or spaces?

**Comment by ScottEwing** [comment]
I think besides the issue of line indentation, this branch looks great! We would definitely want to use spaces, not tabs. As for number of spaces, I'd vote 4 instead of 2 if we're voting. :) :shipit: 

PS, this is my work account.

**Comment by something15525** [comment]
Alright, 4 it is! I'll normalize it and push up, then Scott, if you could do the honors of merging, that would be awesome!

**Comment by something15525** [comment]
Okay, this branch should be ready. :ship:

**Comment by logicplace** [comment]
Okay your changes lgtm, someone else should merge it tho since we were the authors.

**Comment by something15525** [comment]
@ScottEwing ?

**Comment by scotte216** [comment]
Oops. Merged!

**Comment by something15525** [comment]
Yay!

**Pull request merged**
